name: "E2E Testing"
on: [push]
jobs:
  test-e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          npm install -g npm@latest
          npm ci
        
      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test tests/home.spec.ts

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: test-results/
          retention-days: 30